
from controlnode import Controlnode
controlroot = Controlnode();
controlroot.inputresource('0')
controlroot.inputresource('1')
controlroot.inputresource('2')
controlroot.inputresource('3')
controlroot.inputresource('4')
controlroot.inputresource('5')
controlroot.inputresource('6')
controlroot.inputresource('7')
controlroot.inputresource('8')
controlroot.inputresource('9')

controlroot.inputresource('a')
controlroot.inputresource('b')
controlroot.inputresource('c')
controlroot.inputresource('d')
controlroot.inputresource('e')
controlroot.inputresource('f')
controlroot.inputresource('g')
controlroot.inputresource('h')
controlroot.inputresource('i')
controlroot.inputresource('j')
controlroot.inputresource('k')
controlroot.inputresource('l')
controlroot.inputresource('m')
controlroot.inputresource('n')
controlroot.inputresource('o')
controlroot.inputresource('p')
controlroot.inputresource('q')
controlroot.inputresource('r')
controlroot.inputresource('s')
controlroot.inputresource('t')
controlroot.inputresource('u')
controlroot.inputresource('v')
controlroot.inputresource('w')
controlroot.inputresource('x')
controlroot.inputresource('y')
controlroot.inputresource('z')

#print(value)
